image:
  - Visual Studio 2017
build_script:
  - dotnet build src -c Release
test_script:
  - dotnet test src -c Release
branches:
  only:
    - master
    - nuget
pull_requests:
  do_not_increment_build_number: true
artifacts:
  - path: '**\*.nupkg'
nuget:
  disable_publish_on_pr: true
deploy:
  provider: NuGet
  api_key:
    secure: nNWiXk+ZiOOh5sHV/C9Z9pqZ8GFpaQFqAR/P0/t09h81Ppx3xed6VsWd4w7FMn2R
